name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-api
  pull_request:
    branches:
      - main
      - feature-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        pylint app.py APITesting.py main.py

    - name: Run unit tests
      run: |
        pytest APITesting.py

